config/routes.rb
Rails.application.routes.draw do
  get 'pages/landing'

  resources :students
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @students = Student.all
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="btn btn-outline-primary" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-warning ml-2" href="<%= pages_landing_path %>">Landing</a>
      </li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad22</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.1/cerulean/bootstrap.min.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/landing.html.erb
<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :student_email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, id: :student_age, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <h1>Editing Student</h1>

    <%= render 'form', student: @student %>

    <%= link_to 'Show', @student, class: 'btn btn-outline-success mt-2' %> |
    <%= link_to 'Back', students_path, class: 'btn btn-secondary mt-2' %>
  </div>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Destroy', student, method: :delete, 
        data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: 'btn btn-info' %>

app/views/students/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <h1>New Student</h1>

    <%= render 'form', student: @student %>

    <%= link_to 'Back', students_path, class: 'btn btn-secondary mt-2' %>
  </div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<%= link_to 'Edit', edit_student_path(@student), class: 'btn btn-outline-success mt-2' %> |
<%= link_to 'Back', students_path, class: 'btn btn-secondary mt-2' %>